//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id_Car { get; set; }
        public int Make { get; set; }
        public int Model { get; set; }
        public int Fuel { get; set; }
        public string Power { get; set; }
        public Nullable<int> Production_Year { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Sir { get; set; }
    
        public virtual Fuel Fuel1 { get; set; }
        public virtual Model Model1 { get; set; }
        public virtual Make Make11 { get; set; }
    }
}
