//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public int Id_Make { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
